# .github/workflow/release.yml
#
# Based on https://blog.lufia.org/entry/2024/05/10/004259

name: Release

on:
  release:
    types:
    - published
jobs:
  release:
    strategy:
      matrix:
        os:
        - linux
        - darwin
        - windows
        arch:
        - amd64
        - arm64
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Build the package
      run: |
        bindir="$(go env GOPATH)/bin"
        name="$(basename "$PACKAGE_PATH")"

        target="$name"
        if [[ "$(go env GOOS)" = windows ]]
        then
          target="$target.exe"
        fi

        go install -tags netgo -trimpath "$PACKAGE_PATH@$VERSION"
        file="$(find "$bindir" -type f -executable -name "$target")"

        target="$name-$VERSION.$GOOS-$GOARCH"
        if [[ "$(go env GOOS)" = windows ]]
        then
          target="$target.exe"
        fi
        mv "$file" "$INPUT_PATH/$target"
        echo target="$target" >>"$GITHUB_OUTPUT"
      env:
        PACKAGE_PATH: github.com/hnakamur/utc2local-go
        INPUT_PATH: ${{ github.workspace }}
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
        VERSION: ${{ github.ref_name }}
        CGO_ENABLED: 0
      shell: bash
      id: build
    - name: Create the asset of the build artifacts
      uses: actions/upload-artifact@v4
      with:
        tag: ${{ github.ref_name }}
        path: ${{ steps.build.outputs.target }}
        name: utc2local-go-${{ github.ref_name }}.${{ matrix.os }}-${{ matrix.arch }}
        format: ${{ matrix.format }}

  upload:
    needs: release
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: assets
        merge-multiple: true
    - name: Upload the assets to the release
      run: gh release upload -R "$GITHUB_REPOSITORY" "$GITHUB_REF_NAME" assets/*
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
